name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Manual version to release'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Check version
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Current branch: ${{ github.ref_name }}"

          if ! [[ "${{ inputs.version }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "❌ version is not valid"
            exit 1
          fi

      # issue: https://github.com/helm/chart-releaser-action/issues/113
      - name: Force tags download
        run: |
          git pull --tags

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Semantic release
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic
      #   with:
      #     dry_run: true
      #     semantic_version: 18.0.0
      #     extra_plugins: |
      #       @semantic-release/release-notes-generator@10.0.3
      #       @semantic-release/git@10.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump new version
        run: |
          yq -i ".version = \"${{ inputs.version }}\"" "charts/microservice-chart/Chart.yaml"
          git add "charts/microservice-chart/Chart.yaml"
          git commit -m "Bumb microservice chart version ${{ inputs.version }}"
          git push -u origin ${{ github.ref_name }}

      - name: Setup Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
